#!/bin/env bash

# Franklin Souza
# FranklinTech
# Pack's Wallpapers

clear
mkdir $HOME/Wallpapers && clear
cd $HOME/Wallpapers
wget -c "https://cdn-127.anonfiles.com/BfV3B3U6u3/9deaf09b-1636758575/Pack%20Wallpapers.tar.gz"
printf "Download concluído com sucesso!!!" && tar -xvf Pack\ Wallpapers.tar.gz
